services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: edbarber01
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  backend:
    build:
      context: ./
      dockerfile: /back/dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/edbarber01
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL: true
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./
      dockerfile: /front/dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network


volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
