FROM node:21 as builder
WORKDIR /app
COPY ./front ./
RUN npm install --legacy-peer-deps
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist/barbearia-app/browser /usr/share/nginx/html
COPY ./front/nginx.conf /etc/nginx/nginx.conf
COPY ./front/mime.types /etc/nginx/mime.types
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]